server:
  port: 9999
spring:
  application:
    name: springboot-iptv-server
  cloud:
    gateway:
      routes:
        - id: default-route
          uri: https://blog.ambitiousjun.cn
          predicates:
            - Path=/iptv
        - id: refresh-route
          uri: https://blog.ambitiousjun.cn
          predicates:
            - Path=/iptv-refresh
iptv:
  server-config-url: https://example.com/iptv-server.yml
  proxies: # 服务器代理请求直播源
    - host: sas.fenbu.net # 要代理的直播源主机地址
      headers: # 代理请求头
        - origin|https://tingfm.com
        - accept-language|zh-CN,zh;q=0.9
os: mac
